<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com, contato@sigasmart.com.br
 * https://www.sigasmart.com.br
 */
namespace App\Http\Livewire\Admin\Auth;

use App\User;
use Call\LaravelLivewireForms\Auth\Traits\RegistersUsers;
use Call\LaravelLivewireForms\FormComponent;

class RegisterForm extends FormComponent
{
    use RegistersUsers;

    public function query()
    {
        return User::query(); // TODO: Change the autogenerated stub
    }

    public function route(){
        return "users";
    }
}
